# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtDesignerFiles/NewMaterial.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewMaterial(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(524, 112)
        self.groupBox5 = QtWidgets.QGroupBox(Form)
        self.groupBox5.setGeometry(QtCore.QRect(0, 0, 521, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox5.sizePolicy().hasHeightForWidth())
        self.groupBox5.setSizePolicy(sizePolicy)
        self.groupBox5.setStyleSheet("#groupBox5 {\n"
"    border: 2px solid black; /* Толщина и цвет рамки */\n"
"    border-radius: 30px;    /* Радиус закругления */\n"
"    background-color: white; /* Цвет фона (опционально) */\n"
"}\n"
"")
        self.groupBox5.setTitle("")
        self.groupBox5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox5.setObjectName("groupBox5")
        self.label_2 = QtWidgets.QLabel(self.groupBox5)
        self.label_2.setGeometry(QtCore.QRect(201, 11, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox5)
        self.label_3.setGeometry(QtCore.QRect(336, 11, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox5)
        self.textEdit.setGeometry(QtCore.QRect(50, 50, 101, 41))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.groupBox5)
        self.label.setGeometry(QtCore.QRect(60, 10, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox5)
        self.spinBox.setGeometry(QtCore.QRect(199, 51, 91, 41))
        self.spinBox.setObjectName("spinBox")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox5)
        self.doubleSpinBox.setGeometry(QtCore.QRect(336, 51, 91, 41))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.line = QtWidgets.QFrame(self.groupBox5)
        self.line.setGeometry(QtCore.QRect(450, 0, 16, 111))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton = QtWidgets.QPushButton(self.groupBox5)
        self.pushButton.setGeometry(QtCore.QRect(466, 32, 41, 41))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("QtDesignerFiles\\check-128 (1).webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "NewMaterial"))
        self.label_2.setText(_translate("Form", "Влажность"))
        self.label_3.setText(_translate("Form", "Плотность"))
        self.label.setText(_translate("Form", "Название"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_NewMaterial()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())