# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtDesignerFiles/PointWarmChoice.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PointWarmChoice(object):
    def setupController(self, Controller):
        self.Controller = Controller
    def setupUi(self, PointWarmChoice):
        PointWarmChoice.setObjectName("PointWarmChoice")
        PointWarmChoice.resize(814, 625)
        self.groupBox6 = QtWidgets.QGroupBox(PointWarmChoice)
        self.groupBox6.setGeometry(QtCore.QRect(80, 40, 651, 551))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox6.sizePolicy().hasHeightForWidth())
        self.groupBox6.setSizePolicy(sizePolicy)
        self.groupBox6.setStyleSheet("#groupBox6 {\n"
"    border: 2px solid black; /* Толщина и цвет рамки */\n"
"    border-radius: 100px;    /* Радиус закругления */\n"
"    background-color: white; /* Цвет фона (опционально) */\n"
"}\n"
"")
        self.groupBox6.setTitle("")
        self.groupBox6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox6.setObjectName("groupBox6")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox6)
        self.doubleSpinBox.setGeometry(QtCore.QRect(140, 472, 78, 20))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label = QtWidgets.QLabel(self.groupBox6)
        self.label.setGeometry(QtCore.QRect(70, 470, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox6)
        self.label_2.setGeometry(QtCore.QRect(250, 470, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox6)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(290, 472, 78, 20))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox6)
        self.label_3.setGeometry(QtCore.QRect(400, 470, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox6)
        self.spinBox.setGeometry(QtCore.QRect(530, 470, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.startModel = QtWidgets.QPushButton(self.groupBox6)
        self.startModel.setGeometry(QtCore.QRect(210, 495, 201, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startModel.sizePolicy().hasHeightForWidth())
        self.startModel.setSizePolicy(sizePolicy)
        self.startModel.setStyleSheet("#startModel {\n"
"    background-color: blue;    /* Синий фон кнопки */\n"
"    color: white;              /* Белый цвет текста */\n"
"    font-size: 16px;           /* Увеличенный размер текста */\n"
"    border-radius: 10px;       /* Закругление краев */\n"
"    padding: 10px 15px;     /* Отступы */\n"
"margin-top:8px;\n"
"}\n"
"\n"
".parent {\n"
"    overflow: visible;         /* Убедитесь, что элементы не обрезаются */\n"
"}\n"
"\n"
"#startModel::indicator {\n"
"    width: 25px;               /* Увеличенный размер кружка */\n"
"    height: 25px;              /* Увеличенный размер кружка */\n"
"    border: 3px solid white;   /* Белая обводка кружка */\n"
"    background-color: blue;    /* Синий цвет кружка */\n"
"    border-radius: 12px;       /* Закругление кружка */\n"
"}\n"
"\n"
"#startModel::indicator::checked {\n"
"    background-color: white;   /* Белый фон для выбранного состояния */\n"
"    border: 3px solid blue;    /* Синяя обводка выбранного кружка */\n"
"}\n"
"")
        self.startModel.setObjectName("startModel")

        self.retranslateUi(PointWarmChoice)
        QtCore.QMetaObject.connectSlotsByName(PointWarmChoice)

    def retranslateUi(self, PointWarmChoice):
        _translate = QtCore.QCoreApplication.translate
        PointWarmChoice.setWindowTitle(_translate("PointWarmChoice", "PointWarmChoice"))
        self.label.setText(_translate("PointWarmChoice", "Высота:"))
        self.label_2.setText(_translate("PointWarmChoice", "Угл:"))
        self.label_3.setText(_translate("PointWarmChoice", "R-координата:"))
        self.startModel.setText(_translate("PointWarmChoice", "Продолжить"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_PointWarmChoice()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())